// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aibabag.Data;

#nullable disable

namespace aibabag.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("aibabag.Models.AstrologyInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CareerInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoveInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LuckyColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LuckyNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthlyForecast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalityTraits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AstrologyInsights");
                });

            modelBuilder.Entity("aibabag.Models.CompatibilityMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompatibilityDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompatibilityPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationshipTips")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetZodiacSign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TargetZodiacSign", "CalculatedAt");

                    b.ToTable("CompatibilityMatches");
                });

            modelBuilder.Entity("aibabag.Models.DetailedAstrologyInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdventureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimalInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtisticTendencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BossCompatibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessVentures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CareerGrowth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CareerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CareerRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CelebrityMatch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildParenting")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColleagueRelationships")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreativeOutlets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreativityRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DailyForecast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DietaryRecommendations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntertainmentPreferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseRecommendations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyHarmony")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyPlanning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteAnimal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteCuisine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteGenres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteMovieGenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinanceRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinancialOutlook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FriendshipRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendshipTraits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FutureOpportunities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupDynamics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HiddenTalents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricalPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HobbyRecommendations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdealChildTraits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdealFriendType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdealPartnerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestmentAdvice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobFitness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadershipPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LeadershipQualities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoveMatches")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LoveRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LuckRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LuckyDestinations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LuckyFood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LuckyMonthsForWealth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagementStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarriageCompatibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarriageInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeditationAdvice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MentalWellbeing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoneyManagement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthlyForecast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkingAbility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentalRelationships")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastKarma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastLifeInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalGrowth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PetCompatibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RomanceAdvice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiblingDynamics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpiritualPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamworkInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VulnerabilityAreas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WealthInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklyForecast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearlyForecast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DetailedAstrologyInsights");
                });

            modelBuilder.Entity("aibabag.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthDateRawText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDateSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChineseZodiac")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GoogleBirthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("BLOB");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZodiacSign")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("aibabag.Models.AstrologyInsight", b =>
                {
                    b.HasOne("aibabag.Models.User", "User")
                        .WithMany("Insights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aibabag.Models.CompatibilityMatch", b =>
                {
                    b.HasOne("aibabag.Models.User", "User")
                        .WithMany("CompatibilityMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aibabag.Models.DetailedAstrologyInsight", b =>
                {
                    b.HasOne("aibabag.Models.User", "User")
                        .WithMany("DetailedInsights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("aibabag.Models.User", b =>
                {
                    b.Navigation("CompatibilityMatches");

                    b.Navigation("DetailedInsights");

                    b.Navigation("Insights");
                });
#pragma warning restore 612, 618
        }
    }
}
